# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/archiv/AKP/AKP/AKP/AKP.srcs/sources_1/ip/AKP_pel_delay/AKP_pel_delay.xci
# IP: The module: 'AKP_pel_delay' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/archiv/AKP/AKP/AKP/AKP.srcs/sources_1/ip/AKP_pel_delay/AKP_pel_delay.xdc
# XDC: The top module name and the constraint reference have the same name: 'AKP_pel_delay'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/archiv/AKP/AKP/AKP/AKP.srcs/sources_1/ip/AKP_pel_delay/AKP_pel_delay_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AKP_pel_delay'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/archiv/AKP/AKP/AKP/AKP.srcs/sources_1/ip/AKP_pel_delay/AKP_pel_delay.xci
# IP: The module: 'AKP_pel_delay' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/archiv/AKP/AKP/AKP/AKP.srcs/sources_1/ip/AKP_pel_delay/AKP_pel_delay.xdc
# XDC: The top module name and the constraint reference have the same name: 'AKP_pel_delay'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/archiv/AKP/AKP/AKP/AKP.srcs/sources_1/ip/AKP_pel_delay/AKP_pel_delay_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AKP_pel_delay'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
